### ISSUE TITLE
Request for presence

### ISSUE THREAD

**Issue by ctubio** [mattrude/pgpkeyserver-lite#3]
hey @mattrude !
first, thank you so much for your docs and sources.
I used them as a inspiration for https://github.com/ctubio/php-proxy-sks

Now that i start to feel that php-proxy-sks starts working as expected, i was wondering..

Do you agree if i add your project https://github.com/mattrude/pgpkeyserver-lite as a git submodule inside my /skin folder?
Otherwise, i can just maintain a separated copy of your sources in my tree (very bad plan b).
Or otherwise, i can just add a text file with a link to your project (nice plan b).
Or if you dont agree, i can just do nothing (nice plan c).

What are your thoughts?
Thank you for your time,

**Comment by mattrude** [comment]
You are more then welcome to add pgpkeyserver-lite to your project.  I vote plan A; add it as a submodule so it can be maintained.

**Comment by mattrude** [comment]
Also, if you need some peers for your keyserver, let me know and I can add you.

**Comment by ctubio** [comment]
Ok. Cool. I will add it as a submodule. And i will make sure that the current version (or any new release whenever it happens) "just works", so you don't need to worry about thirty-party incompatibilities.

About the lovely peers, im still restarting the keyserver too much frequently, but i will remember your offer as soon as it is stable (will use the sks-devel mailing list first).

(You are the man of the month! :boom:)
byee,
